//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/InputAssets/Player Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Input"",
    ""maps"": [
        {
            ""name"": ""CharacterControls"",
            ""id"": ""51ac8b70-c611-4ec4-8014-06583b4feb62"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""462260de-6f9a-4a2a-8a68-be3eba22bb2b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""35141be2-18e5-43f4-9757-3faf1b0de3ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Melee"",
                    ""type"": ""Button"",
                    ""id"": ""22a9c530-7b85-40bd-beae-cb4d3fa273b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CommandHerd"",
                    ""type"": ""Button"",
                    ""id"": ""94fd5b77-8d39-45ba-b4f4-1d792956575a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClickMelee"",
                    ""type"": ""Button"",
                    ""id"": ""9b49758c-6d06-4c51-b063-feda34de6540"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""daa64030-8b12-4394-b31e-81a093270d22"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""7d150c56-fd22-4ecc-b0b7-52640a039732"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Consumable"",
                    ""type"": ""Button"",
                    ""id"": ""384242c7-7ee9-41b9-a4a0-7b6c532f6d02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityQ"",
                    ""type"": ""Button"",
                    ""id"": ""40cbfd14-b23d-4571-94a1-7a74d07f18dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityE"",
                    ""type"": ""Button"",
                    ""id"": ""25bcd9e3-25eb-46c6-a1ea-2dde6858fbf9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityR"",
                    ""type"": ""Button"",
                    ""id"": ""bf1a84a5-1ace-4bed-9743-923cd6df540a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityMMB"",
                    ""type"": ""Button"",
                    ""id"": ""80247e1b-00b3-4f06-8681-f73d4d1e5f12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilitySHIFT"",
                    ""type"": ""Button"",
                    ""id"": ""29b4d233-d814-4cbc-aafb-5058bcb80888"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityRMB"",
                    ""type"": ""Button"",
                    ""id"": ""d9132ac5-e4c9-460d-96d0-5cf946fdaaa9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""202d17ee-0c01-4a51-9b98-d9edb7817838"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d4940656-8327-45ff-b778-a775129cd760"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""52bbb983-ef7a-4a2e-81d7-076d227d8277"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""59ec7153-613e-4b9b-800d-61d7b46f9dba"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a6775f3e-b3f9-4433-a199-c7bee083a85a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""df4424ca-4f6a-4dda-92b9-f471d98d2edc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cc3736c9-36bd-4d28-878d-f9263e811a9f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""419862f5-d383-457f-938a-006b86cef2f3"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a755ca6-77c8-419a-a404-259b008418b0"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Melee"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dca5412c-c9a4-425e-809d-d7afb47f4562"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CommandHerd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e2c700e-40c9-4660-80db-1efbb0ba1e0c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CommandHerd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cede7c0b-829a-4c1e-a754-df00a4305c3b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickMelee"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60bad274-51dd-42a1-b500-9dded0a2cab1"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e777826-96b4-48a3-ac29-0f1fe5d47df0"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4da62ad-590d-4a68-a420-b35b064a8f4e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45458930-b88e-4b7f-93cb-9ccf9754e27e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Consumable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35553850-e161-4f31-bb74-0fa8fae65e4b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Consumable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97e542e9-027f-4272-8a00-43bb009e4ba8"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Consumable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c78b243-38f8-4d6a-a6ca-b70c21f5cb8c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Consumable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a02ba03e-8d0d-40e5-8c60-f86f641be2ff"",
                    ""path"": ""<Keyboard>/#(Q)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityQ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c4e3c56-e48a-4582-9a74-659715911f70"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityQ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36c966f9-c842-4542-8970-d8a365acae2e"",
                    ""path"": ""<Keyboard>/#(E)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fabf67df-9492-4dcc-a083-1b4a99303de2"",
                    ""path"": ""<Keyboard>/#(R)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f65efc5-835b-4ebf-b070-81ce2f17121e"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityMMB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24db8808-39f4-42c2-a836-184561d91849"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilitySHIFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86f6a6ac-7561-4f9b-96b7-24df165a7e6c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityRMB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UIControls"",
            ""id"": ""2189b50f-e9aa-4300-b793-369eda5b694c"",
            ""actions"": [
                {
                    ""name"": ""ToggleInventory"",
                    ""type"": ""Button"",
                    ""id"": ""d13315e4-5fb0-458d-8472-f79a5cf1e238"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseLoadout0"",
                    ""type"": ""Button"",
                    ""id"": ""b0c07b8a-d430-4471-ab82-8c16e03c131a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseLoadout1"",
                    ""type"": ""Button"",
                    ""id"": ""0cb32015-c3c6-46f7-90f7-c37e8029f4aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseLoadout2"",
                    ""type"": ""Button"",
                    ""id"": ""392c25e7-85a2-4e45-86d1-85000741b106"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseLoadout3"",
                    ""type"": ""Button"",
                    ""id"": ""96c3ad57-f6a1-4bf9-a640-8c4866db2f12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseTab"",
                    ""type"": ""Button"",
                    ""id"": ""6529f88e-8727-4bb4-87bd-72ed8c632951"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseNotification"",
                    ""type"": ""Button"",
                    ""id"": ""4a9f1e38-be71-4fe2-9dee-2d2751d4c3ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""33cb9d9b-3305-49f7-a566-b2bfe652f633"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc247de3-c5a1-4a73-8602-13d0b3e714d0"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseLoadout1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2f48375-f0a6-47d8-9c19-33ef2dad2099"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseLoadout2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c709abe6-d23f-4700-9600-503dc1f21b4a"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseLoadout3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""646af35e-c0d2-4489-941b-f64cdac34bfb"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseLoadout0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4aa4cbd-02b7-41e0-ad49-4ccece344220"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseTab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f33bd58-4925-4686-95a7-bd9ba569e098"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseTab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f377c99e-a1c3-4425-b2be-c46660fef533"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseNotification"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60cb8f51-7b7b-46f0-9d0f-425104305067"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseNotification"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a1ce289-a143-4e76-b1ab-68ade2718551"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseNotification"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DialogueControls"",
            ""id"": ""8804d4a2-06ef-41b1-bd8b-5c8be13e1dd0"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""e24c00e5-a0d2-439f-b5d5-a877bd23b7ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f442927f-48dd-43d9-872b-969b2c4d6661"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterControls
        m_CharacterControls = asset.FindActionMap("CharacterControls", throwIfNotFound: true);
        m_CharacterControls_Move = m_CharacterControls.FindAction("Move", throwIfNotFound: true);
        m_CharacterControls_Dash = m_CharacterControls.FindAction("Dash", throwIfNotFound: true);
        m_CharacterControls_Melee = m_CharacterControls.FindAction("Melee", throwIfNotFound: true);
        m_CharacterControls_CommandHerd = m_CharacterControls.FindAction("CommandHerd", throwIfNotFound: true);
        m_CharacterControls_ClickMelee = m_CharacterControls.FindAction("ClickMelee", throwIfNotFound: true);
        m_CharacterControls_MousePosition = m_CharacterControls.FindAction("MousePosition", throwIfNotFound: true);
        m_CharacterControls_Pause = m_CharacterControls.FindAction("Pause", throwIfNotFound: true);
        m_CharacterControls_Consumable = m_CharacterControls.FindAction("Consumable", throwIfNotFound: true);
        m_CharacterControls_AbilityQ = m_CharacterControls.FindAction("AbilityQ", throwIfNotFound: true);
        m_CharacterControls_AbilityE = m_CharacterControls.FindAction("AbilityE", throwIfNotFound: true);
        m_CharacterControls_AbilityR = m_CharacterControls.FindAction("AbilityR", throwIfNotFound: true);
        m_CharacterControls_AbilityMMB = m_CharacterControls.FindAction("AbilityMMB", throwIfNotFound: true);
        m_CharacterControls_AbilitySHIFT = m_CharacterControls.FindAction("AbilitySHIFT", throwIfNotFound: true);
        m_CharacterControls_AbilityRMB = m_CharacterControls.FindAction("AbilityRMB", throwIfNotFound: true);
        // UIControls
        m_UIControls = asset.FindActionMap("UIControls", throwIfNotFound: true);
        m_UIControls_ToggleInventory = m_UIControls.FindAction("ToggleInventory", throwIfNotFound: true);
        m_UIControls_UseLoadout0 = m_UIControls.FindAction("UseLoadout0", throwIfNotFound: true);
        m_UIControls_UseLoadout1 = m_UIControls.FindAction("UseLoadout1", throwIfNotFound: true);
        m_UIControls_UseLoadout2 = m_UIControls.FindAction("UseLoadout2", throwIfNotFound: true);
        m_UIControls_UseLoadout3 = m_UIControls.FindAction("UseLoadout3", throwIfNotFound: true);
        m_UIControls_CloseTab = m_UIControls.FindAction("CloseTab", throwIfNotFound: true);
        m_UIControls_CloseNotification = m_UIControls.FindAction("CloseNotification", throwIfNotFound: true);
        // DialogueControls
        m_DialogueControls = asset.FindActionMap("DialogueControls", throwIfNotFound: true);
        m_DialogueControls_Click = m_DialogueControls.FindAction("Click", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterControls
    private readonly InputActionMap m_CharacterControls;
    private ICharacterControlsActions m_CharacterControlsActionsCallbackInterface;
    private readonly InputAction m_CharacterControls_Move;
    private readonly InputAction m_CharacterControls_Dash;
    private readonly InputAction m_CharacterControls_Melee;
    private readonly InputAction m_CharacterControls_CommandHerd;
    private readonly InputAction m_CharacterControls_ClickMelee;
    private readonly InputAction m_CharacterControls_MousePosition;
    private readonly InputAction m_CharacterControls_Pause;
    private readonly InputAction m_CharacterControls_Consumable;
    private readonly InputAction m_CharacterControls_AbilityQ;
    private readonly InputAction m_CharacterControls_AbilityE;
    private readonly InputAction m_CharacterControls_AbilityR;
    private readonly InputAction m_CharacterControls_AbilityMMB;
    private readonly InputAction m_CharacterControls_AbilitySHIFT;
    private readonly InputAction m_CharacterControls_AbilityRMB;
    public struct CharacterControlsActions
    {
        private @PlayerInput m_Wrapper;
        public CharacterControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_CharacterControls_Move;
        public InputAction @Dash => m_Wrapper.m_CharacterControls_Dash;
        public InputAction @Melee => m_Wrapper.m_CharacterControls_Melee;
        public InputAction @CommandHerd => m_Wrapper.m_CharacterControls_CommandHerd;
        public InputAction @ClickMelee => m_Wrapper.m_CharacterControls_ClickMelee;
        public InputAction @MousePosition => m_Wrapper.m_CharacterControls_MousePosition;
        public InputAction @Pause => m_Wrapper.m_CharacterControls_Pause;
        public InputAction @Consumable => m_Wrapper.m_CharacterControls_Consumable;
        public InputAction @AbilityQ => m_Wrapper.m_CharacterControls_AbilityQ;
        public InputAction @AbilityE => m_Wrapper.m_CharacterControls_AbilityE;
        public InputAction @AbilityR => m_Wrapper.m_CharacterControls_AbilityR;
        public InputAction @AbilityMMB => m_Wrapper.m_CharacterControls_AbilityMMB;
        public InputAction @AbilitySHIFT => m_Wrapper.m_CharacterControls_AbilitySHIFT;
        public InputAction @AbilityRMB => m_Wrapper.m_CharacterControls_AbilityRMB;
        public InputActionMap Get() { return m_Wrapper.m_CharacterControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterControlsActions set) { return set.Get(); }
        public void SetCallbacks(ICharacterControlsActions instance)
        {
            if (m_Wrapper.m_CharacterControlsActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMove;
                @Dash.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnDash;
                @Melee.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMelee;
                @Melee.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMelee;
                @Melee.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMelee;
                @CommandHerd.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCommandHerd;
                @CommandHerd.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCommandHerd;
                @CommandHerd.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnCommandHerd;
                @ClickMelee.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnClickMelee;
                @ClickMelee.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnClickMelee;
                @ClickMelee.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnClickMelee;
                @MousePosition.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnMousePosition;
                @Pause.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPause;
                @Consumable.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnConsumable;
                @Consumable.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnConsumable;
                @Consumable.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnConsumable;
                @AbilityQ.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityQ;
                @AbilityQ.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityQ;
                @AbilityQ.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityQ;
                @AbilityE.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityE;
                @AbilityE.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityE;
                @AbilityE.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityE;
                @AbilityR.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityR;
                @AbilityR.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityR;
                @AbilityR.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityR;
                @AbilityMMB.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityMMB;
                @AbilityMMB.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityMMB;
                @AbilityMMB.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityMMB;
                @AbilitySHIFT.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilitySHIFT;
                @AbilitySHIFT.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilitySHIFT;
                @AbilitySHIFT.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilitySHIFT;
                @AbilityRMB.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityRMB;
                @AbilityRMB.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityRMB;
                @AbilityRMB.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnAbilityRMB;
            }
            m_Wrapper.m_CharacterControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Melee.started += instance.OnMelee;
                @Melee.performed += instance.OnMelee;
                @Melee.canceled += instance.OnMelee;
                @CommandHerd.started += instance.OnCommandHerd;
                @CommandHerd.performed += instance.OnCommandHerd;
                @CommandHerd.canceled += instance.OnCommandHerd;
                @ClickMelee.started += instance.OnClickMelee;
                @ClickMelee.performed += instance.OnClickMelee;
                @ClickMelee.canceled += instance.OnClickMelee;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Consumable.started += instance.OnConsumable;
                @Consumable.performed += instance.OnConsumable;
                @Consumable.canceled += instance.OnConsumable;
                @AbilityQ.started += instance.OnAbilityQ;
                @AbilityQ.performed += instance.OnAbilityQ;
                @AbilityQ.canceled += instance.OnAbilityQ;
                @AbilityE.started += instance.OnAbilityE;
                @AbilityE.performed += instance.OnAbilityE;
                @AbilityE.canceled += instance.OnAbilityE;
                @AbilityR.started += instance.OnAbilityR;
                @AbilityR.performed += instance.OnAbilityR;
                @AbilityR.canceled += instance.OnAbilityR;
                @AbilityMMB.started += instance.OnAbilityMMB;
                @AbilityMMB.performed += instance.OnAbilityMMB;
                @AbilityMMB.canceled += instance.OnAbilityMMB;
                @AbilitySHIFT.started += instance.OnAbilitySHIFT;
                @AbilitySHIFT.performed += instance.OnAbilitySHIFT;
                @AbilitySHIFT.canceled += instance.OnAbilitySHIFT;
                @AbilityRMB.started += instance.OnAbilityRMB;
                @AbilityRMB.performed += instance.OnAbilityRMB;
                @AbilityRMB.canceled += instance.OnAbilityRMB;
            }
        }
    }
    public CharacterControlsActions @CharacterControls => new CharacterControlsActions(this);

    // UIControls
    private readonly InputActionMap m_UIControls;
    private IUIControlsActions m_UIControlsActionsCallbackInterface;
    private readonly InputAction m_UIControls_ToggleInventory;
    private readonly InputAction m_UIControls_UseLoadout0;
    private readonly InputAction m_UIControls_UseLoadout1;
    private readonly InputAction m_UIControls_UseLoadout2;
    private readonly InputAction m_UIControls_UseLoadout3;
    private readonly InputAction m_UIControls_CloseTab;
    private readonly InputAction m_UIControls_CloseNotification;
    public struct UIControlsActions
    {
        private @PlayerInput m_Wrapper;
        public UIControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleInventory => m_Wrapper.m_UIControls_ToggleInventory;
        public InputAction @UseLoadout0 => m_Wrapper.m_UIControls_UseLoadout0;
        public InputAction @UseLoadout1 => m_Wrapper.m_UIControls_UseLoadout1;
        public InputAction @UseLoadout2 => m_Wrapper.m_UIControls_UseLoadout2;
        public InputAction @UseLoadout3 => m_Wrapper.m_UIControls_UseLoadout3;
        public InputAction @CloseTab => m_Wrapper.m_UIControls_CloseTab;
        public InputAction @CloseNotification => m_Wrapper.m_UIControls_CloseNotification;
        public InputActionMap Get() { return m_Wrapper.m_UIControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIControlsActions set) { return set.Get(); }
        public void SetCallbacks(IUIControlsActions instance)
        {
            if (m_Wrapper.m_UIControlsActionsCallbackInterface != null)
            {
                @ToggleInventory.started -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnToggleInventory;
                @ToggleInventory.performed -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnToggleInventory;
                @ToggleInventory.canceled -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnToggleInventory;
                @UseLoadout0.started -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout0;
                @UseLoadout0.performed -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout0;
                @UseLoadout0.canceled -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout0;
                @UseLoadout1.started -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout1;
                @UseLoadout1.performed -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout1;
                @UseLoadout1.canceled -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout1;
                @UseLoadout2.started -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout2;
                @UseLoadout2.performed -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout2;
                @UseLoadout2.canceled -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout2;
                @UseLoadout3.started -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout3;
                @UseLoadout3.performed -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout3;
                @UseLoadout3.canceled -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnUseLoadout3;
                @CloseTab.started -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnCloseTab;
                @CloseTab.performed -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnCloseTab;
                @CloseTab.canceled -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnCloseTab;
                @CloseNotification.started -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnCloseNotification;
                @CloseNotification.performed -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnCloseNotification;
                @CloseNotification.canceled -= m_Wrapper.m_UIControlsActionsCallbackInterface.OnCloseNotification;
            }
            m_Wrapper.m_UIControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ToggleInventory.started += instance.OnToggleInventory;
                @ToggleInventory.performed += instance.OnToggleInventory;
                @ToggleInventory.canceled += instance.OnToggleInventory;
                @UseLoadout0.started += instance.OnUseLoadout0;
                @UseLoadout0.performed += instance.OnUseLoadout0;
                @UseLoadout0.canceled += instance.OnUseLoadout0;
                @UseLoadout1.started += instance.OnUseLoadout1;
                @UseLoadout1.performed += instance.OnUseLoadout1;
                @UseLoadout1.canceled += instance.OnUseLoadout1;
                @UseLoadout2.started += instance.OnUseLoadout2;
                @UseLoadout2.performed += instance.OnUseLoadout2;
                @UseLoadout2.canceled += instance.OnUseLoadout2;
                @UseLoadout3.started += instance.OnUseLoadout3;
                @UseLoadout3.performed += instance.OnUseLoadout3;
                @UseLoadout3.canceled += instance.OnUseLoadout3;
                @CloseTab.started += instance.OnCloseTab;
                @CloseTab.performed += instance.OnCloseTab;
                @CloseTab.canceled += instance.OnCloseTab;
                @CloseNotification.started += instance.OnCloseNotification;
                @CloseNotification.performed += instance.OnCloseNotification;
                @CloseNotification.canceled += instance.OnCloseNotification;
            }
        }
    }
    public UIControlsActions @UIControls => new UIControlsActions(this);

    // DialogueControls
    private readonly InputActionMap m_DialogueControls;
    private IDialogueControlsActions m_DialogueControlsActionsCallbackInterface;
    private readonly InputAction m_DialogueControls_Click;
    public struct DialogueControlsActions
    {
        private @PlayerInput m_Wrapper;
        public DialogueControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_DialogueControls_Click;
        public InputActionMap Get() { return m_Wrapper.m_DialogueControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DialogueControlsActions set) { return set.Get(); }
        public void SetCallbacks(IDialogueControlsActions instance)
        {
            if (m_Wrapper.m_DialogueControlsActionsCallbackInterface != null)
            {
                @Click.started -= m_Wrapper.m_DialogueControlsActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_DialogueControlsActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_DialogueControlsActionsCallbackInterface.OnClick;
            }
            m_Wrapper.m_DialogueControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
            }
        }
    }
    public DialogueControlsActions @DialogueControls => new DialogueControlsActions(this);
    public interface ICharacterControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnMelee(InputAction.CallbackContext context);
        void OnCommandHerd(InputAction.CallbackContext context);
        void OnClickMelee(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnConsumable(InputAction.CallbackContext context);
        void OnAbilityQ(InputAction.CallbackContext context);
        void OnAbilityE(InputAction.CallbackContext context);
        void OnAbilityR(InputAction.CallbackContext context);
        void OnAbilityMMB(InputAction.CallbackContext context);
        void OnAbilitySHIFT(InputAction.CallbackContext context);
        void OnAbilityRMB(InputAction.CallbackContext context);
    }
    public interface IUIControlsActions
    {
        void OnToggleInventory(InputAction.CallbackContext context);
        void OnUseLoadout0(InputAction.CallbackContext context);
        void OnUseLoadout1(InputAction.CallbackContext context);
        void OnUseLoadout2(InputAction.CallbackContext context);
        void OnUseLoadout3(InputAction.CallbackContext context);
        void OnCloseTab(InputAction.CallbackContext context);
        void OnCloseNotification(InputAction.CallbackContext context);
    }
    public interface IDialogueControlsActions
    {
        void OnClick(InputAction.CallbackContext context);
    }
}
